# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM marcsaric/minimal-notebook

LABEL maintainer="Marc Saric <marc.saric@gmx.de>"

USER root

# FIXME: Add ftp-ssl and setup git-annex

USER $NB_USER
