dist: xenial
language: python
python:
    - 3.7
sudo: required
services:
    - docker
install:
    - pip install --upgrade pip
    - make dev-env
script:
    - set -e
    - make docs
    - make build-test-all DARGS="--build-arg TEST_ONLY_BUILD=1"
